### ISSUE TITLE
playwithmpv服务器报500了，能帮忙看下吗

### ISSUE THREAD

**Issue by LuckyPuppy514** [videoanywhere/playwithmpv#3]
![RN@3N6ML9O%~A8{C~WA~CQG](https://user-images.githubusercontent.com/53246532/157569113-4bb5481d-5a9e-4913-ace4-c21e1f9b8d9b.png)
![image](https://user-images.githubusercontent.com/53246532/157569149-579d168e-6ec7-4e69-a0fd-d48ebb911527.png)

**Comment by LuckyPpy** [comment]
解决了：site-packages\playwithmpv\server.py中
os.environ["HOME"]改成os.environ["USERPROFILE"]

windows环境不存在HOME

**Comment by curlfoxs** [comment]
commit https://github.com/videoanywhere/playwithmpv/commit/34dca5ee55ee2bac3e217949ade733705d2d7a67 已修复
