### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by amronbook** [videoanywhere/playwithmpv#5]
![image](https://user-images.githubusercontent.com/51790146/173191266-f16d4dbd-17c2-490d-b7c7-33597223ca0d.png)

**Comment by amronbook** [comment]
这是什么意思呀，作者大大

**Comment by wullic** [comment]
有cmd的debug信息吗？

**Comment by wullic** [comment]
估计是这个issue导致的，新版本已经修复了。
#4 


可在命令行运行如下命令重新安装：
```
pip uninstall playwithmpv
pip install playwithmpv --user
```

**Comment by curlfoxs** [comment]
那issue我先关了，后面有问题再reopen
